logging.level:
  org.springframework.jdbc: debug
  #  jpa log
  org.hibernate.sql: debug
  org.hibernate.orm.jdbc.bind: trace

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# global paging
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
#        one-indexed-parameters: true index 1부터 시작

